### ISSUE TITLE
tty continuously outputs messages like "sl0: not found" and "ppp0: not found"

### ISSUE THREAD

**Issue by iambumblehead** [GhostBSD/networkmgr#10]
this is an amazingly useful and easy to use software --thank you!

I'm using this in DragonFly BSD and the primary tty continuously outputs messages like "sl0: not found" and "ppp0: not found". Would you recommend a way disabling these interfaces or preventing these messages?

**Comment by ericbsd** [comment]
Yea NetworkMGR was not made for those devices that could be probably solve.

**Comment by ericbsd** [comment]
I have fix that issue in https://github.com/GhostBSD/networkmgr/commit/203f09a66c2e77f3b22d49b92efef5456e34cbec.

**Comment by iambumblehead** [comment]
@ericbsd thank you so much :)
