### ISSUE TITLE
Invalid ssid name if uses blank space

### ISSUE THREAD

**Issue by AandersonL** [GhostBSD/networkmgr#11]
I had a little problem to connect in my network because i have blank space between my ssid, Example: 
ssid: 'my wifi', ifconfig only gets 'my' and dont connect correctly!

So, i solved that making that little change in: 
 `call('doas ifconfig wlan0 ssid %s' % name, shell=True)`
to
 `call('doas ifconfig wlan0 ssid \'%s\'' % name, shell=True)`

Just put a new single quotes in '%s', to ifconfig accept correctly!

**Comment by ericbsd** [comment]
there is also this way to call("doas ifconfig wlan0 ssid '%s'" % name, shell=True). 

Thanks, I will commit the change right away.

**Comment by ericbsd** [comment]
https://github.com/GhostBSD/networkmgr/commit/dc75fd3dc8a5ce80eaf873909fa12d669690cf76
