### ISSUE TITLE
Possibility of an OpenBSD port?

### ISSUE THREAD

**Issue by evitalis** [ghostbsd/networkmgr#15]
Are there plans in the works for this to be used on OpenBSD as well? I have been working on some shell scripts but this would work perfectly. 

One potentially issue I see from their community though is the use of `doas` for most actions. If this is a daemon it shouldn't be needed. Currently the service commands and path to doas would need adjusted for OpenBSD, but that is all I can see from a quick glance.

I plan to work ona  PR as time allows but that may be slow going hence this request.

**Comment by ericbsd** [comment]
If anyone wants to contribute on it for OpenBSD I have no problem, but it is not in my plan to supports OpenBSD.

**Comment by evitalis** [comment]
@ericbsd I no longer use or support OpenBSD. feel free to close this issue if it makes sense.
