### ISSUE TITLE
Does it support KDE plasma 5？

### ISSUE THREAD

**Issue by ykla** [GhostBSD/networkmgr#16]
RT.Sorry to trouble you,but who install it on KDE plasma 5?

**Comment by ericbsd** [comment]
It is A GTK Software that is started to run in the notification tray. I have no idea if it works on Plasma 5 I never use KDE on FreeBSD.

**Comment by PaddyMac** [comment]
I just installed it, and it appears to work under Plasma 5. I'm running FreeBSD 11.2.

**Comment by ericbsd** [comment]
So case closed thanks @PaddyMac
