### ISSUE TITLE
Unable to configure network connection

### ISSUE THREAD

**Issue by willbprog127** [ghostbsd/networkmgr#19]
NetworkMgr works fine to display and enable/disable connections, but I am unable to configure DHCP or static addressing, DNS servers, etc.  Do I need to be part of a certain group for these options to appear?

Thanks :+1:

**Comment by ericbsd** [comment]
It is not an option, that exists right now. It is on the roadmap for the next release. https://issues.ghostbsd.org/issues/100

**Comment by vimanuelt** [comment]
Will close this ticket to create 3 tickets for each feature.
1. Add manual DHCP configuration feature for end user.
2. Add manual Static IP configuration feature for end user.
3. Add manual DNS Server configuration feature for end user.

**Comment by vimanuelt** [comment]
Broken down and reassigned to new tickets.
