### ISSUE TITLE
No icons on FreeBSD in lxqt 0.14.0

### ISSUE THREAD

**Issue by dmoerner** [ghostbsd/networkmgr#20]
This could have some connection to #1 . On FreeBSD with lxqt-panel, I see only a tiny square in the tray, and no icons when I open up the menu (e.g., for signal strength). I installed gnome-icon-theme with no effect.

**Comment by bsdlme** [comment]
Same here. FreeBSD 12.1, networkmgr 3.9.

**Comment by ericbsd** [comment]
I just installed LXQT, and look like the icon it really small probably something due to GTK and QT incompatibility.

**Comment by bsdlme** [comment]
Can you share GTK / QT settings from GhostBSD?

**Comment by ericbsd** [comment]
> Can you share GTK / QT settings from GhostBSD?

There is no setting we do on GhostBSD, LXQT does not render the icon properly.
