### ISSUE TITLE
FreeBSD 10.3 - Command not found

### ISSUE THREAD

**Issue by ciceroschons** [GhostBSD/networkmgr#3]
After install and restart, the network manager icon did not appear.

SO:
10.3-RELEASE
MATE 1.12.0
Doas 5.9p7
Python 2.7.13

#cat /usr/local/etc/sudoers
root ALL=(ALL) ALL
cicero ALL=(ALL) ALL
%wheel ALL=(ALL) ALL

#cat /etc/group
wheel:*:0:root,cicero

#networkmgr
networkmgr: Command not found.

% python2 /usr/local/bin/networkmgr
doas: netcardmgr: command not found  << but the icon appears

**Comment by ericbsd** [comment]
Did you explicitly follow this https://github.com/GhostBSD/networkmgr#installation?
