### ISSUE TITLE
Git version: cannot change WiFi network

### ISSUE THREAD

**Issue by Peter2121** [ghostbsd/networkmgr#33]
FreeBSD 11.3, Enlightenment DE, tint2 tray.
Playing with the Git version, it seems that some additional doas.conf lines are needed - trying to change WiFi network I get the following errors:

```
service netif status not supported
No matching processes belonging to you were found
Successfully initialized wpa_supplicant
ioctl[SIOCSIFFLAGS]: Operation not permitted
wlan0: Failed to initialize driver interface
SSID/MESH ID    BSSID              CHAN RATE    S:N     INT CAPS
ppp-rrr         14:cc:20:e0:b8:d4   11   54M  -74:-95   100 EPS  RSN WME ATH
                6c:38:a1:15:f9:5c   36   54M  -90:-95   100 EP   HTCAP WPA RSN WME BSSLOAD
Bbox-EED837C2   6c:38:a1:15:f9:5d   36   54M  -90:-95   100 EP   HTCAP WPA RSN WME BSSLOAD
ppp-rrr5        14:cc:20:e0:b8:d6   36   54M  -84:-95   100 EP   RSN WME
Bbox-EED837C2   6c:38:a1:15:f9:58    1   54M  -87:-95   100 EP   APCHANREP APCHANREP WPS HTCAP WPA RSN WME BSSLOAD
SFR_D4A8        24:95:04:72:d4:ac    6   54M  -92:-95   100 EP   HTCAP WPS WPA WME
SFR WiFi FON    9a:95:04:72:d4:ad    6   54M  -92:-95   100 E    HTCAP WME
Livebox-4FFC    30:d3:2d:c8:2d:54   11   54M  -91:-95   100 EPS  HTCAP WME ATH WPS RSN WPA
Cannot open or create pidfile: Permission denied
Can't find free bpf: Permission denied
```
Connection remains on the old network.
The version from FreeBSD repository works correctly.

**Comment by ericbsd** [comment]
you need to be in the wheel group, and it is using sudo now.

**Comment by Peter2121** [comment]
I am in the wheel group (if not - the version from FreeBSD repository does not work neither).
What is the sudo config needed? Some words in readme would be appreciated ;)
BTW, what is the reason of changing doas->sudo?

**Comment by ericbsd** [comment]
none of the if you are in wheel and use sudo to start the network manager.

**Comment by Peter2121** [comment]
Is it necessary now to start network manager as root? If so, it is really bad on security level. And probably there are some problems at DBus level as AppIndicator version started with sudo does not work. What is the reason of forgetting doas approach? The actual version from FreeBSD repository does not need sudo to start...

**Comment by ericbsd** [comment]
NetworkMgr is made for GhostBSD first and the newer version is not in ports yet an not sure is I will even bring it there doas was removed because of all the logs that it did generate, with sudo if run as root and it is more simple and work for GhostBSD at the moment.

**Comment by Peter2121** [comment]
Thanks a lot for this clarification.
