### ISSUE TITLE
Reconnect to Wifi after Router Reboot

### ISSUE THREAD

**Issue by liangcorp** [ghostbsd/networkmgr#39]
I recently rebooted my router. I wasn't logged on my FreeBSD laptop since I was using it as a server. I realise that the networkmgr didn't reconnect to the wifi afterwards. I had to login and manually select the SSID and reconnect.

**Comment by ericbsd** [comment]
Not sure, but the FreeBSD network stack should do that automaticaly.

**Comment by ericbsd** [comment]
Networkmgr is just an interface to interact with ifconfig network service and wpa-supplicant.
