### ISSUE TITLE
Feature request: doas support

### ISSUE THREAD

**Issue by Maselko** [ghostbsd/networkmgr#48]
As doas is becoming more popular, is it possible to add an option of installing with doas?

**Comment by ericbsd** [comment]
It was using doas in that pass, but with the FreeBSD ports team not letting setup.py or the port auto-add config to doas.conf, I resorted to sudo. It would be nice if doas could have some like doas.d.

**Comment by Maselko** [comment]
So, is there any way to use this with doas? If so, would you mind telling what to add to config to doas.conf? Thank you for your help.
