### ISSUE TITLE
rc.conf.local logic doesn't work as intended yet

### ISSUE THREAD

**Issue by driesmp** [ghostbsd/networkmgr#53]
I'll investigate this myself, this is just a tracker so I remind myself.
I think we might need to add some logic to net_api.py for rc.conf.local, eg in functions wired_card_added and wifi_card_added.

The reason that it doesn't work as intended for me yet is because I have defined all interfaces identically as networkmgr would've done in rc.conf.local, but it still writes to rc.conf.

**Comment by ericbsd** [comment]
There was a PR to fix that issue and the newest NerwotkMgr does not have that problem.

**Comment by driesmp** [comment]
I see, thanks. Could you push this fix to FreeBSD ports? Or are you waiting on the rework as you mentioned in the individual PR before creating a new tag.

**Comment by ericbsd** [comment]
I will I have some minor improvement that I want to get in, but I am not sure how FreeBSD users will like to have networkmgr override default devd entry.

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/networkmgr/blob/master/src/setupnic.conf

**Comment by driesmp** [comment]
I did a quick scan, per FreeBSD hierarchy, this setupnic.conf file should go in /usr/local/etc/devd/.
When I look at some other files present, maybe the correct naming convention should be networkmgr.conf, see image below.

![image](https://user-images.githubusercontent.com/32487486/115733841-8872bd00-a389-11eb-963c-19c333bb8c73.png)

Furthermore it seems that the default devd.conf in /etc/devd.conf already includes the wifi regex for us.
![image](https://user-images.githubusercontent.com/32487486/115734060-b5bf6b00-a389-11eb-81ac-57b755d1bc61.png)

I think the file is fine to ship as is for FreeBSD. It might be nice if you could check to remove the double wifi-regex definitions, maybe move them from this file to /etv/devd.conf in GhostBSD?

**Comment by ericbsd** [comment]
I was not aware if wifi-driver-regex of devd.conf would have work that is why I did add in setupnic.conf.

I remove it and test it when I get my improvement in.

**Comment by ericbsd** [comment]
That should do it https://github.com/ghostbsd/networkmgr/commit/c5c543db57dff1d2fbc47ab97f6cdd880ab9c29e

**Comment by ericbsd** [comment]
https://github.com/freebsd/freebsd-ports/commit/6022b5e24de357464bdb3db9b7863ad56bee3072

**Comment by ericbsd** [comment]
@driesmp feel free to open tickets if there any other problems.
