### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/networkmgr#55]
```text
root@mowa219-gjp4-8570p:~ # grep -i python /usr/ports/UPDATING | grep 3.8
  The default version of python3 and python was switched to 3.8.
root@mowa219-gjp4-8570p:~ # 
```

An update to https://github.com/GhostBSD/networkmgr#user-content-installation might be appropriate. Would you like me to draft a pull request?

**Comment by ericbsd** [comment]
It is not yet in GhostBSD ports.
```
ericbsd@ericbsed-ghostbsd-pc ~> grep -i python /usr/ports/UPDATING | grep 3.8
ericbsd@ericbsed-ghostbsd-pc ~ [0|1]> 
```

**Comment by ericbsd** [comment]
You can make a pull request. It will be merge when 3.8 gets merge in.

**Comment by andigi89** [comment]
updated the python version in the readme
