### ISSUE TITLE
llvm version upgrade with real downgrade

### ISSUE THREAD

**Issue by arturbac** [ghostbsd/networkmgr#60]
First of all the pkg build of kdevelop is linked against the oldest llvm in tree 9.0 instead of newer one with better libclang c++17 and c++20 code parsing support.

Second changing in /etc/make.conf
DEFAULT_VERSIONS+=llvm=12
allows building kdevelop against llvm12 with better libclang and deisntallation of llvm9, but pkg is forcing install of older llvm 9 as and UPGRADE to llvm12

Installed packages to be UPGRADED:
        llvm: 12 -> 90 [GhostBSD]

**Comment by ericbsd** [comment]
What that has to do with networkmgr?
