### ISSUE TITLE
[Feature] Automatic switchover

### ISSUE THREAD

**Issue by Crushless** [ghostbsd/networkmgr#64]
When using a notebook, and you often have to switch locations (sometimes with available wired networking, sometimes without), networkmgr should automatically switch between wired and WiFi network interfaces, and prioritize a wired interface, if connected. If a network interface is setup with DHCP, this should be handled automatically. Nameserver and default route should also be automatically adjusted to use the desired interface.

Today, you have to manually disable one interface, and sometimes the other interface too and re-enable the desired interface to get it working. In an modern, dynamic working environment this is not very convenient.

**Comment by ericbsd** [comment]
Note to myself devd should handle this with
```
notify 0 {
	match "system"		"IFNET";
	match "type"		"LINK_DONW";
	media-type		"ethernet";
       *
}
```
and
```
notify 0 {
	match "system"		"IFNET";
	match "subsystem"	"!(usbus|wlan)[0-9]+";
	match "type"		"LINK_DONW";
	*
};
```

**Comment by ericbsd** [comment]
Completed
