### ISSUE TITLE
USB tether support

### ISSUE THREAD

**Issue by danboid** [GhostBSD/networkmgr#8]
I make heavy use of the USB network tethering feature of my Android phone. After connecting my phone via USB and enabling USB tethering on my phone, to connect to it under FreeBSD I have to run:

`dhclient ue0`

It would be nice if networkmgr could support auto-detection of and connection to USB ethernet connections.

**Comment by ericbsd** [comment]
I am looking forward to implementing that.

**Comment by ericbsd** [comment]
I have added support for multiple cards including ue0 in https://github.com/GhostBSD/networkmgr/commit/203f09a66c2e77f3b22d49b92efef5456e34cbec see https://ibb.co/iQ26cm wired @ is ue0.
