### ISSUE TITLE
[Feature]: Show signal strength

### ISSUE THREAD

**Issue by danboid** [ghostbsd/networkmgr#81]
It would be handy if networkmgr could show the strength of wifi signals.

It doesn't look like ifconfig supplies this data but apparently wlanstats can be used for this. wlanstats could be included with ghostbsd and BSD users could see their wifi signal strength by mousing over the networkmgr tray icon or see it in the networkmgr connection menu next to each connection if they have wlanstats installed.

**Comment by ericbsd** [comment]
If I understand, what you want is the signal strength number on the mouseover?

**Comment by danboid** [comment]
That's right, thanks!

**Comment by ericbsd** [comment]
The only thing left is to update the tag and port.
