### ISSUE TITLE
doas.conf without full path

### ISSUE THREAD

**Issue by mirehi** [GhostBSD/networkmgr#9]

**Comment by rakor** [comment]
Having no full paths for the cmd set in doas.conf means that every user permitted to run the command can run any script with root-privileges. So in your example every user beeing in :wheel can run anything with root-privileges without being prompted for a passwort. All she has to do is change her own $PATH to show up the prepared script first.

**Comment by rakor** [comment]
The Problem should be gone (haven't tested yet) .
https://github.com/slicer69/doas/pull/13
